hook.Add("AddToolMenuCategories", "AddToolMenuCategories_VehicleCustomizer", function()
    spawnmenu.AddToolCategory("Utilities", "Vehicule Customizer", "Vehicule Customizer")
end)

local function VehicleCustomizer_Panel(CPanel)
    CPanel:ClearControls()
    CPanel:AddControl("Header", { Description = "Vehicule Customizer allows you to generate a code for a vehicle with the props you put. This is used for example to create a flashing light ramp for example"})
    CPanel:AddControl("TextBox", {Label = "Vehicle Name", Command = "vc_name", MaxLength = "50"})
    CPanel:AddControl("TextBox", {Label = "Vehicle Category", Command = "vc_category", MaxLength = "50"})
    CPanel:AddControl("TextBox", {Label = "Vehicle Information", Command = "vc_information", MaxLength = "50"})
    CPanel:AddControl("TextBox", {Label = "Props ID", Command = "vc_props", MaxLength = "200"})

    CPanel:Help("")
    local vector = vgui.Create("DCollapsibleCategory")
    vector:SetLabel("Vector")
    vector:SetSize(100, 100)
    vector:Dock(TOP)

    CPanel:AddItem(vector)

    local CategoryContentVector = vgui.Create("DPanelList")
    CategoryContentVector:SetAutoSize(true)
    CategoryContentVector:SetDrawBackground(false)
    CategoryContentVector:SetSpacing(1)
    CategoryContentVector:SetPadding(2)
    vector:SetContents(CategoryContentVector)

    // Slider
    local SliderX = vgui.Create("DNumSlider", CPanel)
    SliderX:SetText("X")
    SliderX.Label:SetDark(true)
    SliderX:SetMin(-500)
    SliderX:SetMax(500)
    SliderX:SetDecimals(3)
    SliderX:SetConVar("vc_x")
    CategoryContentVector:AddItem(SliderX)

    local SliderY = vgui.Create("DNumSlider", CPanel)
    SliderY:SetText("Y")
    SliderY.Label:SetDark(true)
    SliderY:SetMin(-500)
    SliderY:SetMax(500)
    SliderY:SetDecimals(3)
    SliderY:SetConVar("vc_y")
    CategoryContentVector:AddItem(SliderY)

    local SliderZ = vgui.Create("DNumSlider", CPanel)
    SliderZ:SetText("Z")
    SliderZ.Label:SetDark(true)
    SliderZ:SetMin(-500)
    SliderZ:SetMax(500)
    SliderZ:SetDecimals(3)
    SliderZ:SetConVar("vc_z")
    CategoryContentVector:AddItem(SliderZ)

    CPanel:Help("")
    local angle = vgui.Create("DCollapsibleCategory")
    angle:SetLabel("Angle")
    angle:SetSize(100, 100)
    angle:Dock(TOP)
    
    CPanel:AddItem(angle)

    local CategoryContentAngle = vgui.Create("DPanelList")
    CategoryContentAngle:SetAutoSize(true)
    CategoryContentAngle:SetDrawBackground(false)
    CategoryContentAngle:SetSpacing(1)
    CategoryContentAngle:SetPadding(2)
    angle:SetContents(CategoryContentAngle)

    // Slider
    local SliderPitch = vgui.Create("DNumSlider", CPanel)
    SliderPitch:SetText("Pitch")
    SliderPitch.Label:SetDark(true)
    SliderPitch:SetMin(-360)
    SliderPitch:SetMax(360)
    SliderPitch:SetDecimals(3)
    SliderPitch:SetConVar("vc_pitch")
    CategoryContentAngle:AddItem(SliderPitch)

    local SliderYaw = vgui.Create("DNumSlider", CPanel)
    SliderYaw:SetText("Yaw")
    SliderYaw.Label:SetDark(true)
    SliderYaw:SetMin(-360)
    SliderYaw:SetMax(360)
    SliderYaw:SetDecimals(3)
    SliderYaw:SetConVar("vc_yaw")
    CategoryContentAngle:AddItem(SliderYaw)

    local SliderRoll = vgui.Create("DNumSlider", CPanel)
    SliderRoll:SetText("Roll")
    SliderRoll.Label:SetDark(true)
    SliderRoll:SetMin(-360)
    SliderRoll:SetMax(360)
    SliderRoll:SetDecimals(3)
    SliderRoll:SetConVar("vc_roll")
    CategoryContentAngle:AddItem(SliderRoll)

    CPanel:AddControl("Button", { Text = "Visual", Command = "object_creator_vehicle_visual"})
    CPanel:AddControl("Button", { Text = "Generate code", Command = "object_creator_vehicle_generate_code" })

end

hook.Add("PopulateToolMenu", "PopulateToolMenu_VehicleCustomizer", function()
    spawnmenu.AddToolMenuOption("Utilities", "Vehicule Customizer", "Vehicule Customizer", "Vehicule Customizer", "", "", VehicleCustomizer_Panel)
end)

CreateClientConVar("vc_name", "", false, false)
CreateClientConVar("vc_category", "", false, false)
CreateClientConVar("vc_information", "", false, false)
CreateClientConVar("vc_props", "", false, false)

CreateClientConVar("vc_x", 0, false, false)
CreateClientConVar("vc_y", 0, false, false)
CreateClientConVar("vc_z", 0, false, false)

CreateClientConVar("vc_pitch", 0, false, false)
CreateClientConVar("vc_yaw", 0, false, false)
CreateClientConVar("vc_roll", 0, false, false)

